// This file is auto-generated by @hey-api/openapi-ts

export { askQuestionAskPost, listSyllabiSyllabiGet, type Options, rootGet, uploadSyllabusUploadPost } from './sdk.gen';
export type { AskQuestionAskPostData, AskQuestionAskPostError, AskQuestionAskPostErrors, AskQuestionAskPostResponses, BodyUploadSyllabusUploadPost, ClientOptions, HttpValidationError, ListSyllabiSyllabiGetData, ListSyllabiSyllabiGetResponses, RootGetData, RootGetResponses, UploadSyllabusUploadPostData, UploadSyllabusUploadPostError, UploadSyllabusUploadPostErrors, UploadSyllabusUploadPostResponses, UserQuery, ValidationError } from './types.gen';
