// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { AskQuestionAskPostData, AskQuestionAskPostErrors, AskQuestionAskPostResponses, ListSyllabiSyllabiGetData, ListSyllabiSyllabiGetResponses, RootGetData, RootGetResponses, UploadSyllabusUploadPostData, UploadSyllabusUploadPostErrors, UploadSyllabusUploadPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Upload Syllabus
 *
 * Upload syllabus PDF
 */
export const uploadSyllabusUploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadSyllabusUploadPostData, ThrowOnError>) => (options.client ?? client).post<UploadSyllabusUploadPostResponses, UploadSyllabusUploadPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Ask Question
 *
 * Ask a question about uploaded syllabus
 */
export const askQuestionAskPost = <ThrowOnError extends boolean = false>(options: Options<AskQuestionAskPostData, ThrowOnError>) => (options.client ?? client).post<AskQuestionAskPostResponses, AskQuestionAskPostErrors, ThrowOnError>({
    url: '/ask',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Syllabi
 *
 * List all uploaded syllabi
 */
export const listSyllabiSyllabiGet = <ThrowOnError extends boolean = false>(options?: Options<ListSyllabiSyllabiGetData, ThrowOnError>) => (options?.client ?? client).get<ListSyllabiSyllabiGetResponses, unknown, ThrowOnError>({ url: '/syllabi', ...options });
