// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_upload_syllabus_upload_post
 */
export type BodyUploadSyllabusUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * UserQuery
 */
export type UserQuery = {
    /**
     * Namespace
     */
    namespace: string;
    /**
     * Query
     */
    query: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadSyllabusUploadPostData = {
    body: BodyUploadSyllabusUploadPost;
    headers: {
        /**
         * Api-Key
         */
        'api-key': string;
    };
    path?: never;
    query: {
        /**
         * Namespace
         */
        namespace: string;
    };
    url: '/upload';
};

export type UploadSyllabusUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadSyllabusUploadPostError = UploadSyllabusUploadPostErrors[keyof UploadSyllabusUploadPostErrors];

export type UploadSyllabusUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AskQuestionAskPostData = {
    body: UserQuery;
    headers: {
        /**
         * Api-Key
         */
        'api-key': string;
    };
    path?: never;
    query?: never;
    url: '/ask';
};

export type AskQuestionAskPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AskQuestionAskPostError = AskQuestionAskPostErrors[keyof AskQuestionAskPostErrors];

export type AskQuestionAskPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListSyllabiSyllabiGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/syllabi';
};

export type ListSyllabiSyllabiGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
